apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: prod
spec:
  ports:
  - port: 8080
  selector:
    zone: prod
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchlabels:
      zone: prod
      app: auth-service
  template:
    metadata:
      namespace: prod
      labels:
        zone: prod
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service-image
          envFrom:
          - secretRef:
              name: users-db-creds
          - configMapRef:
              name: users-db-config
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth-network-policy
  namespace: prod
spec:
  pod-selector:
    zone: prod
    app: auth-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          zone: prod
          app: mainpage-service
  - from:
    - podSelector:
        matchLabels:
          zone: prod
          app: trades-service
  egress:
  - to:
    - podSelector:
        matchLabels:
          zone: prod
          app: mainpage-service
  - to:
    - podSelector:
        matchLabels:
          zone: prod
          app: trades-service
  - to:
    - ipBlock:
        cidr: broker-host # url брокера сообщений
    ports:
    - port: broker-port # port брокера сообщений
  - to: # По логике это должно разрешить приложению обращаться к DNS серверу
    - namespaceSelector: {}
    