apiVersion: v1
kind: Service
metadata:
  name: trades-service
  namespace: prod
spec:
  ports:
  - port: 8080
  selector:
    zone: prod
    app: trades-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchlabels:
      zone: prod
      app: trades-service
  template:
    metadata:
      namespace: prod
      labels:
        zone: prod
        app: trades-service
    spec:
      containers:
        - name: trades-service
          image: trades-service-image
          envFrom:
          - configMapRef:
              name: trades-db-config
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trades-network-policy
  namespace: prod
spec:
  pod-selector:
    zone: prod
    app: trades-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          zone: prod
          app: mainpage-service
  - from:
    - podSelector:
        matchLabels:
          zone: prod
          app: auth-service
  egress:
  - to:
    - podSelector:
        matchLabels:
          zone: prod
          app: mainpage-service
  - to:
    - podSelector:
        matchLabels:
          zone: prod
          app: auth-service
  - to: # По логике это должно разрешить приложению обращаться к DNS серверу
    - namespaceSelector: {}